Create db context, update controller and service
jimjja/backend-upskilling-context pull request #2
Opened 2021-04-16 22:12 UTC by mmohamed-and

2021-04-18 12:06 UTC, jimjja requested changes

2021-04-18 12:06 UTC, jimjja commented on Services/BeverageRepository.cs
>          public IEnumerable<Beverage> GetById(string id)
If Id is unique you will only have 1 beverage per id. You should be returning single Beverage here

2021-04-18 12:06 UTC, jimjja commented on Services/BeverageRepository.cs
> +            _dbContext.SaveChanges();
Try to use async where possible. This way you are releasing Threads and not delaying further requests.

2021-04-18 12:06 UTC, jimjja commented on Services/BeverageRepository.cs
> +            _dbContext.SaveChanges();
Try to use async where possible. This way you are releasing Threads and not delaying further requests.

2021-04-18 12:06 UTC, jimjja commented on Services/BeverageRepository.cs
> +            _dbContext.SaveChanges();
Try to use async where possible. This way you are releasing Threads and not delaying further requests.

2021-04-18 12:06 UTC, jimjja commented on ShalekKavy.Api.csproj
> +    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.32" />
What is this Nuget used for?

2021-04-18 12:06 UTC, jimjja commented on Context/BeverageContext.cs
> +        public BeverageContext(DbContextOptions<BeverageContext> options) : base(options) { }
Where do you define the unique primary key for each beverage? Each item in the database needs to have a unique primary key.

2021-04-29 19:24 UTC, mmohamed-and commented on ShalekKavy.Api.csproj
> +    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.32" />
Removed

2021-06-22 17:20 UTC, merged